# ❤️ Funding Information for Hotspot Shield VPN Offline Setup Assistant

# GitHub Sponsors
github: [Hotspot-Shield-Offline]

# Open Collective
# open_collective: hotspot-shield-offline

# Ko-fi
# ko_fi: hotspotshieldoffline

# Tidelift
# tidelift: npm/hotspot-shield-offline

# Community Bridge
# community_bridge: 

# Liberapay
# liberapay: hotspot-shield-offline

# IssueHunt
# issuehunt: Hotspot-Shield-Offline

# Patreon
# patreon: hotspot-shield-offline

# Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/hotspotshieldoffline']

# PayPal
# custom: ['https://paypal.me/hotspotshieldoffline']

# Custom funding URLs
custom: [
  'https://github.com/sponsors/Hotspot-Shield-Offline',
  'https://hotspot-shield-offline.github.io/support'
] 